name: "CI"

on:
  pull_request:
    branches: [main]

jobs:

   build-and-test:
      uses: ./.github/workflows/Build-Tests.yml
      with:
        build-number: ${{ github.run_number }}
      secrets: inherit

